reactiveui/refit

- Rebracer.xml
- Refit-VisualStudio.sln
- Refit-VisualStudio.sln.DotSettings
This should make it a bit easier for people to follow the conventions. :cop:
Fixes #98
> R# and Rebracer settings files

- .gitignore
- Refit/Attributes.cs
- Refit/RefitSettings.cs
- Refit/RequestBuilderImplementation.cs
- Refit/RestService.cs
Add a built-in way of doing authenticated requests with tokens and also enable use of ModernHttpClient
> Authenticated request handling and ModernHttpClient support

- Refit/RequestBuilderImplementation.cs
> Dispose response stream.

- InterfaceStubGenerator/Program.cs
- Refit/RequestBuilderImplementation.cs
This fixes a typo and should address the test error.
> Fixes from tests

- Refit/RequestBuilderImplementation.cs
- Refit/RestService.cs
Adding these properties makes it easy to debug failed calls.
> Add URL and HTTP method to the ApiException

- Refit-Tests/MultipartTests.cs
- Refit-Tests/RefitStubs.cs
- Refit/RequestBuilderImplementation.cs
This fixes several multipart request issues in #267
> Multipart fix

- InterfaceStubGenerator/InterfaceStubGenerator.cs
- fixes https://github.com/paulcbetts/refit/issues/116
- fixes https://github.com/paulcbetts/refit/issues/134
- fixes https://github.com/paulcbetts/refit/issues/300
please merge this ;)
Regads from Berlin
> Fixing #116, #134, #300 with the same reason

- Refit.Tests/RequestBuilder.cs
- Refit/Attributes.cs
- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
This should fix #362 by allowing to use `[Body(StreamMethod.Pull)]`.
> Allow switching to Pull stream method

- README.md
> Add docs for buffering body content

- Refit.Tests/InterfaceStubGenerator.cs
- Refit.Tests/RefitStubs.Net46.cs
- Refit.Tests/RefitStubs.NetCore2.cs
- Refit.Tests/RequestBuilder.cs
- Refit.Tests/RestService.cs
- Refit/Attributes.cs
- Refit/RequestBuilderImplementation.cs
Fix for https://github.com/paulcbetts/refit/issues/329
> Add support for controlling how string body parameters are serialized

- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
> Query string parameter fixes

- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
> Fix bool query params

- README.md
- Refit.Tests/RequestBuilder.cs
- Refit/Attributes.cs
- Refit/RequestBuilderImplementation.cs
PR for issue https://github.com/paulcbetts/refit/issues/93
> Collection formatting

- version.json
this will let us deploy any time.
> move to cd versioning

- Refit.HttpClientFactory/Refit.HttpClientFactory.csproj
> Set PrivateAssets explicitly so build is included transitively

- README.md
There are six built-in annotations! :)
> Added unmentioned PATCH verb to documentation

- README.md
> add nuget & myget badges

- InterfaceStubGenerator.Core/InterfaceStubGenerator.cs
- Refit.Tests/RequestBuilder.cs
- Refit/Attributes.cs
*Micro contribution:*
- `OptionsAttribute` has been created;
- Test **HttpMethod** name for `OptionsAtrtibute`;
> Options Attribute

- samples/Meow.sln
- samples/Meow/Meow.csproj
- samples/Meow/Middleware/HttpClientDiagnosticsHandler.cs
- samples/Meow/Program.cs
- samples/Meow/Responses/BreedsResponse.cs
- samples/Meow/Services/CatsService.cs
- samples/Meow/Services/ITheCatsAPI.cs
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
docs
this is the application as presented at https://twitter.com/GeoffreyHuntley/status/1108818097954144257
> docs: added sample application

- Refit/XmlContentSerializer.cs
> fixes #643 add xmlserializer cache

- CODE_OF_CONDUCT.md
- Directory.build.props
- Refit.Tests/GitHubApi.cs
- Refit.Tests/InheritedGenericInterfacesApi.cs
- Refit.Tests/InheritedInterfacesApi.cs
NA - No functional impact
NA - No functional impact
NA - No functional impact
NA - No functional impact
NA - No functional impact
> Housekeeping: Updated references to DotNetFoundation and URLs

- Refit.Tests/RefitStubs.Net46.cs
- Refit.Tests/RefitStubs.NetCore2.cs
So if I check it in, it won't keep annoying me.
Not much - some generated code in the tests that has apparently never been checked in.
To generate these and suggest them to me on every commit after I run the tests.
Not doing that.
Nothing. It's just tests and they run with the code there.
_Neither of the above apply._
> Running the tests keeps generating this code

- Refit.Tests/RefitStubs.Net46.cs
- Refit.Tests/RefitStubs.NetCore2.cs
- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
> Fix #761: Serialize IEnumerable query parameters correctly.

- Refit.Tests/MultipartTests.cs
- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
> Dictionary key fix

- Refit/targets/refit.targets
> Update targets to ensure outputs and file writes are set correctly

- Refit.Tests/Refit.Tests.csproj
- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
> Get rid of query shift parameter and rely on value from dictionary key

- Refit.Tests/Refit.Tests.csproj
Removes the need for StrongNamer
> Update to MockHttp client with strong name

- Refit.HttpClientFactory/HttpClientFactoryExtensions.cs
- Refit/RefitSettings.cs
- Refit/RestService.cs
- azure-pipelines.yml
> Support handlers in AddRefitClient and document use of HttpClient

- Refit.Tests/RefitStubs.Net46.cs
- Refit.Tests/RefitStubs.NetCore2.cs
- Refit.Tests/RefitStubs.NetCore3.cs
- Refit.Tests/RestService.cs
- Refit/RequestBuilderImplementation.cs
> Custom query prop

- Refit.Tests/RefitStubs.Net46.cs
- Refit.Tests/RefitStubs.NetCore2.cs
- Refit.Tests/RefitStubs.NetCore3.cs
- Refit.Tests/RestService.cs
- Refit/RequestBuilderImplementation.cs
> Ensure we have an emtpy byte array so that a content-length of 0 is sent

- _config.yml
- stylesheets/pygment_trac.css
- stylesheets/styles.css
Along with the settings change, this PR fixes the GitHub Pages to generate from `master` instead of the `gh-pages` branch, so that we'll get an up-to-date page
> Fix GitHub Pages

- Refit.Tests/RefitStubs.Net46.cs
- Refit.Tests/RefitStubs.NetCore2.cs
- Refit.Tests/RefitStubs.NetCore3.cs
- Refit.Tests/RestService.cs
- Refit/RestService.cs
> Base address fix

- Directory.build.props
> Include icon in the nuget package

- Refit.Tests/ResponseTests.cs
- Refit/ApiException.cs
- Refit/RequestBuilderImplementation.cs
> Wrap Deserialization exceptions as an ApiException

- Refit.Tests/RequestBuilder.cs
- Refit/RestMethodInfo.cs
> Fix for multi template parameter use

- InterfaceStubGenerator.Core/InterfaceStubGenerator.cs
- Refit.Tests/InterfaceStubGenerator.cs
- Refit.Tests/RestService.cs
> Prefix our local vars with ______ to prevent collisions

- Refit.Tests/SerializedContentTests.cs
- Refit/Refit.csproj
- Refit/SystemTextJsonContentSerializer.cs
> Use HttpContent json serialization extensions for perf and correctness

- README.md
- Refit.Newtonsoft.Json/NewtonsoftJsonContentSerializer.cs
- Refit.Tests/MultipartTests.cs
- Refit.Tests/SerializedContentTests.cs
- Refit.Tests/XmlContentSerializerTests.cs
- Refit/ApiException.cs
- Refit/FormValueMultimap.cs
- Refit/JsonContentSerializer.cs
- Refit/RefitSettings.cs
- Refit/RequestBuilderImplementation.cs
- Refit/SystemTextJsonContentSerializer.cs
- Refit/XmlContentSerializer.cs
Reflect the nature of what the serializer is for.
> Rename IContentSerializer to IHttpContentSerializer 

- README.md
Add README badges for the new `Refit.Newtonsoft.Json` package.
Package has no badge.
Package has a badge.
Nothing.
> Add Refit.Newtonsoft.Json badges

- README.md
- Refit/targets/refit.targets
Fixes #1085 #1080 by blocking the build.
> Add error case for packages.config to prevent runtime issues

- Refit/SystemTextJsonContentSerializer.cs
> Update inferred types converter for 5.0

- InterfaceStubGenerator.Core/InterfaceStubGenerator.cs
- Refit.Tests/InheritedGenericInterfacesApi.cs
> Fix issue where explicit or override wasn't being passed correctly to the generic constraints writer

- README.md
- docs update (README.md)
- Fixes https://github.com/reactiveui/ReactiveUI/issues/2711
There is a typo in "and DeserializeAsync<T> -> FromHttp**Contnent**Async<T>"
> Update README.md fix typo FromHttpContnentAsync

- README.md
> Fix NuGet package link for Serilog.Exceptions.Refit doc

- README.md
Add an example of how to use the JSON source generator in .NET 6 with Refit (https://github.com/reactiveui/refit/issues/1277#issuecomment-983637859).
> Add note about JSON source generator

- README.md
Fix example code issue in README.md.
> Fix example syntax, add paren.

- README.md
> Fix missing syntax highlighting

- Directory.Build.props
- LICENSE
- Refit.Benchmarks/Refit.Benchmarks.csproj
- Refit.HttpClientFactory/Refit.HttpClientFactory.csproj
- Refit.Newtonsoft.Json/Refit.Newtonsoft.Json.csproj
- Refit.Tests/InterfaceStubGenerator.cs
- Refit.Tests/MultipartTests.cs
- Refit.Tests/Refit.Tests.csproj
- Refit.Tests/RequestBuilder.cs
- Refit.Xml/Refit.Xml.csproj
- Refit.sln
- Refit/ApiResponse.cs
- Refit/Buffers/PooledBufferWriter.Stream.NETStandard21.cs
- Refit/Buffers/PooledBufferWriter.Stream.cs
- Refit/HttpContentExtensions.cs
- Refit/Refit.csproj
- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
Fix build for new target
Update packages
**What is the current behaviour?**
Old Unsupported Targets
**What is the new behaviour?**
New and supported targets
Removed support for old targets
**Please check if the PR fulfils these requirements**
> housekeeping: Update Targets, Fix build, Update relevant packages

- .devcontainers/Dockerfile
- .devcontainers/devcontainer.json
- .devcontainers/post-create.sh
Adds a DevContainer to the project so people don't have to install things locally to build the project
N/A
N/A
N/A
N/A
> Add a DevContainer

- .github/workflows/release.yml
- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit.Benchmarks/Refit.Benchmarks.csproj
- Refit.HttpClientFactory/HttpClientFactoryExtensions.cs
- Refit.HttpClientFactory/Refit.HttpClientFactory.csproj
- Refit.HttpClientFactory/SettingsFor.cs
- Refit.Newtonsoft.Json/NewtonsoftJsonContentSerializer.cs
- Refit.Tests/InterfaceStubGenerator.cs
- Refit.Tests/Refit.Tests.csproj
- Refit.Tests/RequestBuilder.cs
- Refit.Tests/RestService.cs
- Refit/ApiException.cs
- Refit/ApiResponse.cs
- Refit/Attributes.cs
- Refit/JsonContentSerializer.cs
- Refit/MultipartItem.cs
- Refit/PushStreamContent.cs
- Refit/Refit.csproj
- Refit/RefitSettings.cs
- Refit/RequestBuilder.cs
- Refit/RestMethodInfo.cs
update
missing Xml Documentation warnings throughout code base
Removed need for Xml Documentation in tests and benchmarks
Refactor code ensuring tests remain operational
None expected
> Housekeeping Update tests to remove need for comments

- version.json
Update
closes #1403 
closes #1598 
closes #1602  
closes #1684
closes #1671 
closes #1384 
closes #1389 
closes #1261 
closes #1333 
closes #1541 
closes #1258 
Some small additions to the public API
> Ship 7.1.0

- Refit/ApiResponse.cs
- Refit/RequestBuilderImplementation.cs
Revert #1705
Revert #1672 
closes #1729 
Related to #1744 
Reverted to previous
Functionality reverted
> Revert #1705

- Refit.Tests/API/ApiApprovalTests.Refit.DotNet6_0.verified.txt
- Refit.Tests/API/ApiApprovalTests.Refit.DotNet8_0.verified.txt
- Refit.Tests/API/ApiApprovalTests.cs
- Refit.Tests/API/ApiExtensions.cs
- Refit.Tests/Refit.Tests.csproj
Update
The API is not monitored which can lead to incorrect release versions being set
API Tests added for Net 6 and net 8
None, added tests only
> Housekeeping: Add API tests

- version.json
Patch for issues raised with 7.1.0
> Housekeeping Update version for release

- .github/workflows/ci-build.yml
- .github/workflows/release.yml
> Housekeeping Update build

- .github/workflows/release.yml
> Housekeeping Update release.yml

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit.GeneratorTests/Fixture.cs
- Refit.GeneratorTests/Incremental/IncrementalGeneratorRunReasons.cs
- Refit.GeneratorTests/Incremental/IncrementalTest.cs
- Refit.GeneratorTests/Incremental/TestHelper.cs
Added incremental generator tests for #1791
- Tests should fail until I add incremental generation.
> feat: add incremental generator tests

- Refit.GeneratorTests/Fixture.cs
- Ensure that generator tests use most recent version of stub generator.
> chore: target correct StubGenerator

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit/UniqueName.cs
Fixing some typos with some comments and in some methods and params.
N/A
Typos are fixed.
Nothing
> Fix some typos in the codebase

- Refit.GeneratorTests/InterfaceTests.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.DisposableTest#IGeneratedInterface.g.verified.cs
- Added `GeneratedTest` for interfaces that inherit from `IDisposable`
> feat: add `IDisposable` test

- InterfaceStubGenerator.Roslyn41/InterfaceStubGenerator.Roslyn41.csproj
Actually update `Microsoft.CodeAnalysis.CSharp`, see #1828
> chore: update to `Microsoft.CodeAnalysis.CSharp` to `4.1.0`

- Refit.GeneratorTests/InterfaceTests.cs
- Refit.GeneratorTests/ReturnTypeTests.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.InterfaceWithGenericConstraint#IGeneratedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.GenericConstraintReturnTask#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.GenericStructConstraintReturnTask#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.GenericUnmanagedConstraintReturnTask#IGeneratedClient.g.verified.cs
Rel #1791
Will have to be updated after #1861
> feat: added source gen tests for generic constraints

- Refit.Tests/API/ApiApprovalTests.Refit.DotNet6_0.verified.txt
- Refit.Tests/API/ApiApprovalTests.Refit.DotNet8_0.verified.txt
> Housekeeping Fix API Tests

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit/ApiException.cs
- Refit/CamelCaseUrlParameterKeyFormatter.cs
- Refit/PushStreamContent.cs
- Refit/RestMethodInfo.cs
Update
Some code warnings resolved
None expected
> Housekeeping fix some of the code analyser warnings

- InterfaceStubGenerator.Shared/DiagnosticDescriptors.cs
- Refit.GeneratorTests/Incremental/FunctionTest.cs
- Refit.GeneratorTests/Incremental/GenericTest.cs
- Refit.GeneratorTests/Incremental/IncrementalGeneratorRunReasons.cs
- Refit.GeneratorTests/Incremental/InheritanceTest.cs
- Refit.GeneratorTests/Incremental/TestHelper.cs
- Add more incremental tests
- Reduce the size of #1864 by moving related fixes to this PR
- Split the tests up into separate files
Rel #1864
> feat: add more incremental tests

- Refit.GeneratorTests/Refit.GeneratorTests.csproj
- Refit.GeneratorTests/_snapshots/InterfaceTests.NonRefitMethodShouldRaiseDiagnostic.verified.txt
- Refit.GeneratorTests/_snapshots/MethodTests.MethodsWithGenericConstraints.verified.txt
- Updated `Verify.SourceGenerators`
- Accepted modified tests
> chore: upgrade `Verify.SourceGenerators` and update tests

- README.md
Minor; Fix path for groupid (about case insensitive) in readme
> Fix path for groupid (about case insensitive) in readme

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.Shared.projitems
> typo: `WellKnownTYpes` to `WellKnownTypes`
