reactiveui/refit

- .gitignore
- InterfaceStubGenerator/Diagnostics.cs
- InterfaceStubGenerator/Program.cs
> Don't barf on readonly files if contents haven't changed

- Refit/RequestBuilderImplementation.cs
- Refit/RestService.cs
This should allow projects that use the Refit library directly (i.e. other PCLs) to catch `ApiException`.
This is super lazy, but putting `ApiException` in `RestService.cs` means I don't have to change 230958 project files.
Fixes #126.
> Moved ApiException into the Portable project

- Refit-Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
This PR contains the fixes for both of the outstanding header related bugs (#121 and #136).
* Adding of all headers is now deferred until the body parameter has been added to the request. This means `Content` is there and we can add headers to it.
* We now only try to add to the content headers collection if adding to the request headers collection failed.
> Header fixes

- Refit-Tests/Refit-Tests-Net45.csproj
- Refit-Tests/packages.Refit-Tests-Net45.config
Adding the NUnit VS Test Adapter nuget to the test project removes the need to have the NUnit VSIX pre-installed in VS to run unit tests
> Add nunit test adapter to VS so VSIX isn't required

- InterfaceStubGenerator/InterfaceStubGenerator.cs
- Refit-Tests/InterfaceStubGenerator.cs
- Refit-Tests/RefitStubs.cs
Fixes #180 by passing through arguments exactly as specified.
> Allow reserved words in param names

- README.md
I thought I was clever: instead of creating a custom HttpClientHandler I instead created a custom HttpClient. I assumed that overriding HttpClient.SendAsync would accomplish the same result. I was clearly wrong. 
I added a note to the proper section of README.md to help other people avoid my mistake. If you think this warning is valuable then I'd be happy to iterate on the exact wording of the message.
> Update README.md to contain a warning, so that others do not make my mistake

- Refit/targets/refit.targets
In the `Linux` or `Mac` platform, when using the `dotnet cli` to build the project, it will cause the runtime to throw `System.InvalidOperationException: {name} doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.`
This PR can fix this problem.
> Fixed a path separator error on a non-Windows platform.

- Refit/PushStreamContent.cs
- Refit/RequestBuilderImplementation.cs
On very large JSON payloads, it maybe be useful not to copy the entire thing into a string before trying to deserialize it. So this uses streams and JSON reader to deserialize.
> Minimize memory pressure by not always copying json payload to string

- README.md
- Refit.Tests/FormValueDictionaryTests.cs
- Refit/Attributes.cs
- Refit/FormValueDictionary.cs
This adds support for Json.NET's `JsonPropertyAttribute` if present on a
property when using it to generate a request as a form post.
If both `AliasAsAttribute` and `JsonPropertyAttribute` are present,
`AliasAsAttribute` takes precedence.
I also added some tests for `FormValueDictionary`.
Fixes #330.
> Use JsonPropertyAttribute for aliasing form parameter names

- README.md
- Refit.Tests/MyQueryParams.cs
- Refit.Tests/RestService.cs
- Refit/Attributes.cs
- Refit/RequestBuilderImplementation.cs
I have the need like in #315 to use an Object or Dictionary as Queryparamters.
With this Pull Request this is now possible
```
public class MySimpleQueryParams
{
public string FirstName { get; set; }
[AliasAs("lName")]
public string LastName { get; set; }
}
public class MyComplexQueryParams
{
public string FirstName { get; set; }
public string LastName { get; set; }
[AliasAs("Addr")]
public Address Address { get; set; } = new Address();
public Dictionary<string, object> MetaData { get; set; } = new Dictionary<string, object>();
public List<object> Other { get; set; } = new List<object>();
}
public class Address
{
[AliasAs("Zip")]
public int Postcode { get; set; }
public string Street { get; set; }
}
```  
--------------------
```
public interface IHttpBinApi<TResponse, in TParam, in …
```
> Added feature for 'DynamicQueryParameters'

- Refit.Tests/Refit.Tests.csproj
- Refit/Refit.csproj
Added quotations to the statements surrounding the MSBuildThisFileDirectory variables to allow projects to be built from directories that contain spaces.
Resolves Issue #393
> Added quotations to MSBuildThisFileDirectory variables

- README.md
A couple of tiny spelling things in the readme I spotted.
> very minor spelling changes

- Refit.Tests/FormValueDictionaryTests.cs
- Refit.Tests/RequestBuilder.cs
- Refit/Attributes.cs
- Refit/FormValueDictionary.cs
- Refit/RefitSettings.cs
- Refit/RequestBuilderImplementation.cs
Fixes #411 and #415.
`QueryAttribute` now has a Format property that works for both FormUrlEncoded values and for url encoded values.
> Skip null urlencoded form

- Refit.Tests/RequestBuilder.cs
- Refit/HttpUtility.cs
- Refit/Refit.csproj
- Refit/RequestBuilderImplementation.cs
Fixes #298 
Uses `Uri.EscapeDataString` as having the best escaping
https://stackoverflow.com/questions/602642/server-urlencode-vs-httputility-urlencode/47877559#47877559
> Url Encoding fixes

- Refit.Tests/RequestBuilder.cs
- Refit.Tests/RestService.cs
- Refit/Attributes.cs
- Refit/RefitSettings.cs
- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
Fixes #404 by restoring the buffered default. Also adds a global option in the refit settings to be unbuffered.
> Default to buffered

- .vsts-shared.yml
- README.md
- Refit.HttpClientFactory/HttpClientFactoryExtensions.cs
- Refit.HttpClientFactory/Refit.HttpClientFactory.csproj
- Refit.Tests/Refit.Tests.csproj
- Refit.sln
- Refit/Refit.csproj
This is to prevent adding a lot of dependencies to projects not using HTTP Client Factory and enable it for ASP.NET Core running on .NET 4.6.1.
> Split extensions into separate project

- Refit/ApiResponse.cs
Expose the content headers also in the ApiResponse.
Fixes #577
> ApiResponse property ContentHeaders

- Refit/RestMethodInfo.cs
This ought to help developers diagnose where the error occurred. The current stack trace provides no actionable information and requires going through the whole Interface searching for violations.
```
Unhandled Exception: System.ArgumentException: URL has parameter member, but no method parameter matches
at Refit.RestMethodInfo.BuildParameterMap(String relativePath, List`1 parameterInfo) in D:\a\1\s\Refit\RestMethodInfo.cs:line 143
at Refit.RestMethodInfo..ctor(Type targetInterface, MethodInfo methodInfo, RefitSettings refitSettings) in D:\a\1\s\Refit\RestMethodInfo.cs:line 64
at Refit.RequestBuilderImplementation`1..ctor(RefitSettings refitSettings) in D:\a\1\s\Refit\RequestBuilderImplementation.cs:line 58
at Refit.RequestBuilderFactory.Create[T](RefitSettings settings) in …
```
> Provide additional information during errors

- Refit.Tests/FormValueDictionaryTests.cs
- Refit.Tests/FormValueMultimapTests.cs
- Refit/Attributes.cs
- Refit/FormValueDictionary.cs
- Refit/FormValueMultimap.cs
- Refit/RefitSettings.cs
- Refit/RequestBuilderImplementation.cs
When form encoding objects that have a property that is an IEnumerable type, use the QueryAttribute and it's CollectionFormat to determine how to encode the object.
In general, this feature could be fleshed out much more deeply. Future work could include respecting custom formats and delimiters specified on the QueryAttribute, as well as support for collections stored in dictionaries that are form encoded.
>  Add support for url form encoding collections

- Refit.Tests/MultipartTests.cs
- Refit.Tests/SerializedContentTests.cs
- Refit/RequestBuilderImplementation.cs
This fixes an issue that was discovered after pull request #571 was merged to master (MyGet version 4.6.66).
A request which contains a body that should be serialized (and is not a multi-part request) will deadlock in the PushStreamContent at: https://github.com/reactiveui/refit/blob/3fce69b9a7a59a98cf607c7e5c62876e4dcd1165/Refit/PushStreamContent.cs#L142
The PushStreamContent content type provides a stream to write to, but in order for it to complete the request it blocks until the stream is closed. The original implementation did this implicitly because a StreamWriter was used within a using block:
https://github.com/reactiveui/refit/blob/e2e797552b34f2071bc4833280cf3d61150d97bd/Refit/RequestBuilderImplementation.cs#L474-L481
I've added additional tests to make sure that the request …
> Fixed deadlock when serializing content

- README.md
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Docs update
**What is the current behavior? (You can also link to an open issue here)**
The docs does not explain how to send a string as a `StringContent` in the body content.
**What is the new behavior (if this is a feature change)?**
The docs explains how to send a string as a `StringContent` taking into account #425
Nothing
> Update docs because of #425

- Refit.Tests/ResponseTests.cs
- Refit/ApiException.cs
> fix #641 NullReferenceException on Error, when Response.Content.Headers is null

- README.md
- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
Feature
Round-tripping route parameter syntax is a new feature from [ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#differences-from-earlier-versions-of-routing):
Forward slashes aren't encoded when using a double-asterisk (\*\*) catch-all parameter syntax.
During link generation, the routing system encodes the value captured in a double-asterisk (\*\*) catch-all parameter (for example, {**myparametername}) except the forward slashes.
Route | Param | Link
----- | ----- | ----
/search/{**page} | page = "admin/products" | /search/admin/products …
> Support round-tripping route parameter syntax

- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
Bug fix for #687.
Nullable<T> and DateTime types are handled as complex POCO parameters and therefore their properties are added incorrectly to querystrings.
Structs are explicitly handled as simple types and flattened with ToString(). Further, fixed a break where no option for CollectionFormat in querystring collections, results in a loop counter increase, and therefore an off-by-X error (compensated with a counter in the URL parser).
Also, replaced the dictionary key referencing with ElementAt calls for correct index location.
All tests pass.
> Fixes #687

- README.md
There was some confusion in #693 on what "redefinition" of headers means and how it applies to headers with different names.
I've added some documentation which should make this clearer.
Fixes #693
> Clarify header "redefinition"

- Refit.Tests/RequestBuilder.cs
- Refit/RestMethodInfo.cs
Bug fix
A request like :
`[Header("Authorization")] string authorization, int id, [Query(CollectionFormat.Multi)] string[] someArray`
With first a dynamic header, after some query param and in the end one or several Array Query param cause an exception in RestMethodInfo.cs line 124 for duplicate key in QueryParameterMap
We have to place Array in first and header(s) in the end but it's not a "production" solution
Order is not a potential issue, all params are add in QueryParameterMap without duplicate key
Maybe other Get request with query params but all tests are OK
- a new test was add, and the …
> BugFix/ Get order params with Array

- Refit.Tests/RequestBuilder.cs
- Refit/CachedRequestBuilderImplementation.cs
Fix cache key generation in CachedRequestBuilderImplementation
https://github.com/reactiveui/refit/issues/769
Generic and method arguments in cache key use type name without namespace
Generic and method arguments in cache key use full type name
> Fix cache key construct for CachedRequestBuilderImplementation

- README.md
- Refit.Tests/ResponseTests.cs
- Refit/ProblemDetails.cs
Updates the ProblemDetails to support extensions to the spec. This behaves the same as the MS implementation of ProblemDetails extensions: https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/ProblemDetails.cs#L62
This means additional properties on the response will be populated in the new Extensions property.
I have chosen to not change the behaviour of the Errors property in case it's a breaking change for other users.
Extension problem details extension properties are ignored
Extension properties on the problem details response are populated in to new property
It shouldn't cause any regressions with this being additive. …
> feat: Add support for ProblemDetails extensions

- README.md
- Refit.Tests/RequestBuilder.cs
- Refit/Attributes.cs
- Refit/RequestBuilderImplementation.cs
Unescape Querystring parameters #277
All query parameters are escaped by default.
Default behavior can be overridden by an attribute guard.
Query string behavior.
N/A
Big thanks to @deesejohn for originally opening this & submitting a PR that I can't re-open.
> Unescape Querystring parameters #277

- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
This PR modifies the Refit request builder to handle serialization of query objects that contain `IEnumerable` properties. This PR addresses the following issues:
https://github.com/reactiveui/refit/issues/587
https://github.com/reactiveui/refit/issues/522
Currently, an `IEnumerable` property on a query object will translate to the query string as the type name. For example, the following query object
```
class QueryObject
{
IEnumerable<int> TestIntCollection { get; set; }
}
```
will translate as `?testIntCollection=System.Int32%5B%5D`.
`IEnumerable` properties on query objects will be serialized in the same manner as `IEnumerable` parameters passed directly.
**What might this …
> handle serialization for query objects with IEnumerable properties

- README.md
- Refit.Tests/FormValueMultimapTests.cs
- Refit.Tests/RefitStubs.Net46.cs
- Refit.Tests/RefitStubs.NetCore2.cs
- Refit.Tests/RequestBuilder.cs
- Refit/Attributes.cs
- Refit/CollectionFormat.cs
- Refit/FormValueMultimap.cs
- Refit/RefitSettings.cs
- Refit/RequestBuilderImplementation.cs
fixes #840 
Allow specifying default `CollectionFormat` in RefitSettings.
`CollectionFormat` is needed to be set for each query parameter if non-csv is needed.
You can specify `CollectionFormat` in `RefitSettings`, which will be applied unless explicitly specified in `QueryAttribute`.
> Allow specifying default CollectionFormat

- Refit.Tests/RefitStubs.Net46.cs
- Refit.Tests/RefitStubs.NetCore2.cs
- Refit.Tests/RestService.cs
- Refit/RestMethodInfo.cs
Fixes #802 
Allows any casing in the parameter binding to the object
- [ x] Tests for the changes have been added (for bug fixes / features)
> Fix for #802 casing bug on object bound to url

- Refit.Tests/RequestBuilder.cs
- Refit/ApiResponse.cs
- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
It's fixing #545 by making `ApiResponse` implement interface `IApiResponse` and `IApiResponse<T>`. 
The rationale behind it is that `IApiResponse` interface allows to access the `ApiResponse`'s various properties without requiring a strongly typed variable. `IApiResponse<T>` gives the additional access to the content and easier/simpler testing.
A byproduct of the PR/refactor is that the result no longer needs boxing to be returned.
1. `ApiResponse<T>` with no interface
1. `ApiResponse<T>` has `IApiResponse<T>` an `IApiResponse` implemented
2. `Task<IApiResponse<T>>`, `Task<IApiResponse>`, `IObservable<IApiResponse<T>>`, `IObservable<IApiResponse>` would all be valid return types …
> Added interfaces to ApiResponse

- Refit.Tests/RequestBuilder.cs
- Refit.Tests/RestService.cs
- Refit/RestService.cs
Fixes #823 by ensuring that a trailing / is trimmed on an HttpClient provided base address. This was already the case for string supplied urls.
> Trim trailing / for HttpClient-supplied base addresses

- Refit.Tests/RefitStubs.Net46.cs
- Refit.Tests/RefitStubs.NetCore2.cs
- Refit.Tests/RefitStubs.NetCore3.cs
- Refit.Tests/RestService.cs
- Refit/RequestBuilderImplementation.cs
Reverts reactiveui/refit#863
No reason to send 0 length content length if there are no specific content-headers that need to be sent.
Content-Length is only required for HTTP/1.0, not 1.1+
> Revert "Ensure we have an emtpy byte array so that a content-length of 0 is sent"

- README.md
Since 1.4 support is dropped, update README.md accordingly.
> Replace .NET Standard 1.4 with 2.0 in README.md

- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
Fixes #894
a) If query attribute is present on query object property, value is simply converted ToString.
b) `CollectionFormat` (both in `RefitSettings` and in `QueryAttribute`) is ignored when used on query object property. Interesting enough, it differs depending on item type - for enum or int it is Csv (because that is default), for object - Multi (because that how it is defined in `BuildQueryMap` method - no idea why).
a) Value is formatted to string only when explicit Format is defined in Query attribute.
b) Collections in query objects are formatted same as regular query collections - accounting for CollectionFormat in RefitSettings and in QueryAttribute.
**What might this …
> Fix query collection format inside object

- Refit.Tests/FormValueMultimapTests.cs
- Refit/FormValueMultimap.cs
Fixes handling of CollectionFormat in RefitSettings for FormValueMultimap.
If CollectionFormat in RefitSettings is Csv, Ssv or Tsv, and explicit CollectionFormat is not specified in QueryAttribute, collection delimiter is `|`.
Handles appropriately - `,` for Ccv, ` ` for Ssv, `\t` for Tsv. 
> Fix default CollectionFormat for FormValueMultimap

- README.md
Adds documentation about the `ApiResponse<T>` return type and shows examples on how to retrieve response meta data (like response headers and status code) from this return type. I have added this documentation in response to the question I asked in the "Issues" section. This PR fixes #872 
Documentation about this particular return type doesn't exist.
Documentation for this return type has been added.
It won't break anything
None
> Added documentation and examples for the ApiResponse<T> return type.

- Refit.Tests/SerializedContentTests.cs
- Refit/SystemTextJsonContentSerializer.cs
Specify the `Content-Length`, as it is known, when serializing JSON using System.Text.Json for compatibility with systems that do not support chunked encoding.
Otherwise to leverage the new deserializer while maintaining compatibility for serialization in my application, I would have to wrap the content serializer in a custom implementation (because it has no virtual methods to override) and revert to the serialization behaviour I had for System.Text.Json before the new content serializer was available:
```csharp
public Task<HttpContent> SerializeAsync<T>(T item)
{
string json = JsonSerializer.Serialize(item, SerializerOptions);
var content = new StringContent(json, Encoding.UTF8, "application/json");
return …
```
> Specify Content-Length when serializing JSON with System.Text.Json

- Refit.HttpClientFactory/HttpClientFactoryExtensions.cs
Fixing issue #745
Unable to resolve a service after non-generic registration (AddRefitClient(typeof(IMyService)) vs AddRefitClient<IMyService>())
No more issue
Nothing
> Fixing issue #745

- README.md
- Refit/targets/refit.targets
Fixes #942
This PR introduces the `RefitDisableGenerateRefitStubs` MSBuild property to allow for the `GenerateRefitStubs` to be skipped when other source generators based on roslyn are running.
- ~~[ ] Tests for the changes have been added (for bug fixes / features)~~
> fix: Allow for GenerateRefitStubs to be disabled with RefitDisableGenerateRefitStubs

- Refit/RestMethodInfo.cs
Add more information about exception in verify url method
If url don't start with '/', refit throw exception that "URL path {relativePath} must be of the form '/foo/bar/baz'". 
The only one thing that this method check - if path start with '/'. If it's start with '/' than we will have at least two parts, so second check make no sense.
> refactor: change verify url method exception message

- Refit/XmlContentSerializer.cs
Feature
`XmlContentSerializer` won't pass default namespace to `XmlSerializer`'s constuctor
`XmlContentSerializer` will pass default namespace to `XmlSerializer`'s constuctor. If there's no default namespace specified, then default behavior (using `null` as the default namespace) will be used.
It won't break any existing code in theory.
> Support Xml default namespace

- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
Bug fix
Issue #575 method parameter cannot be mapped to both path member and a custom header.
Should not affect any existing code.
> allow HeaderAttribute on parameters used in request path members

- README.md
- Refit.Tests/RequestBuilder.cs
- Refit/Attributes.cs
- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
This fixes the issue [BUG] AuthorizeAttribute does not add a header to the request #946
In short: currently, the AuthorizeAttribute simply doesn't work. 
More in detail: there was an attempt to add an invalid header key, for example "Authorization: Bearer ", and a token as the value. This resulted in nothing being added at all.
Now the AuthorizeAttribute isn't tightly coupled to the headers, but it's a self-contained Attribute instead, which allows us to build the correct Header and value in the RequestBuilderImplementation class.
May be something in rest info method could get read incorrectly.
However, I have fixed the query parameters map to …
> fix [BUG] AuthorizeAttribute does not add a header to the request #946

- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
Bug fix
In the current version (5.2.1), dictionary query parameters with non-string keys throw an exception: `'Unable to cast object of type 'Example.Enum' to type 'System.String'.'`.
Additionally, if the dictionary parameter is part of a complex object, the dictionary is serialized as `?DictionaryPropertyName=%5BKey%2C%20Value%5D`.
This latter issue is reported [here](https://github.com/reactiveui/refit/issues/971).
The current query mapping code for IDictionary properties assumes that the dictionary key type is a string. This PR explicitly calls `ToString()` on the key before storing its value to the query map.
For dictionaries that are a property on a complex query object, …
> Fix dictionary query request mapping

- Refit.Tests/RefitStubs.Net46.cs
- Refit.Tests/RefitStubs.Net5.cs
- Refit.Tests/RefitStubs.NetCore2.cs
- Refit.Tests/RefitStubs.NetCore3.cs
- Refit.Tests/RestService.cs
- Refit/Buffers/PooledBufferWriter.Stream.NETStandard21.cs
- Refit/Buffers/PooledBufferWriter.Stream.cs
Refit might not write everything to the outgoing http stream depending on buffer size and the total amount of data it should sent. This PR fixes that.
Should I also create a PR for 5.2.1, since it's a pretty critical bug, I'd think?
Unsure how to create a good unit/integration test for this - any help would be appreciated.
> Fixes issue #952 - did not write everything to output stream

- Refit.Tests/RestService.cs
Fix new test: Refit 5.2 does not use CamelCasing by default.
> Fix new test: Refit 5.2 does not use CamelCasing by default.

- Refit/targets/refit.targets
No error, if the current version is equals the RefitMSBuildMinVersion
Fix the issue #1037
Allow to compile with the minimum MSBuild version (currently 16.8.0)
Only a version bigger than the minimal version is allowed.
The minimal version is allowed.
Nothing
> Change the condition to check the MSBuild version

- README.md
- Refit.Tests/MultipartTests.cs
- Refit.Tests/RequestBuilder.cs
- Refit/Buffers/PooledBufferWriter.Stream.NETStandard21.cs
- Refit/Buffers/PooledBufferWriter.Stream.cs
- Refit/HttpContentExtensions.cs
- Refit/HttpRequestMessageProperties.cs
- Refit/RequestBuilderImplementation.cs
- Refit/SystemTextJsonContentSerializer.cs
This adds the target interface type to the HttpMessageRequest so that a Delegating Handler can take action based on what the interface is.
Allows #1036 to be implemented using a delegating handler.
> Add interface type to HttpMessageRequest.Options

- README.md
This is a Readme update that seems to have an error or maybe just not updated after API change.
The API described in Readme does not seem to exist and not even used in the same readme further.
Not applicable
Not applicable
Nothing, it's just readme update
> Fixed the wrong API call in Readme.md used with dotnet DI

- InterfaceStubGenerator.Core/InterfaceStubGenerator.cs
- Refit.Tests/InheritedInterfacesApi.cs
- Refit.Tests/InterfaceStubGenerator.cs
- Refit.Tests/RestService.cs
Fixes #1061 for cases when the top-level interface declares refit methods and the base interfaces don't.
Does not handle a case where there's three or more interfaces, and a base interface adds the Refit attributes from something it derives from.
> Generate non-implicit impls for top-level interfaces

- InterfaceStubGenerator.Core/InterfaceStubGenerator.cs
- Refit.Tests/InterfaceStubGenerator.cs
> Update output filenames to end in .g.cs to indicate they're generated.

- InterfaceStubGenerator.Core/InterfaceStubGenerator.cs
- Refit.Tests/InterfaceStubGenerator.cs
- Refit.Tests/Refit.Tests.csproj
@sharwell I'd appreciate a code review
> Add logic to emit #nullable in the generated files if required

- Refit.Tests/RequestBuilder.cs
- Refit/RefitSettings.cs
- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
If fixes the bug #1099.
When the body is serialized (with JsonContent), the data is not buffered because the JsonContent doesn't implement the `TryComputeLength` method (https://github.com/dotnet/runtime/blob/9c3fc566eb916434f8bfe6974e4ddc21ba6e7ff6/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/JsonContent.cs#L55)
The settings `RefitSettings.Buffered` is only used when the `Body` attribute is set without the property `Buffered` defined and has no effect when the `Body` attribute missing. The buffering is always disabled when the attribute is missing.
The request content is buffered, if the buffering is active.
The `RefitSettings.Buffered` is by default equals to …
> Really Buffered JsonContent when buffered is set

- README.md
- Refit.HttpClientFactory/HttpClientFactoryExtensions.cs
- Refit.HttpClientFactory/SettingsFor.cs
- Refit.Tests/HttpClientFactoryExtensionsTests.cs
Feature
Currently it is not possible to influence refit settings using other services in the `IServiceProvider` and everything must be know ahead of time.  This isn't always ideal or possible.
Two new overloads have been added to `AddRefitClient` that take `Func<IServiceProvider, RefitSettings?>? settingsAction`.  This is resolved as a singleton when requesting the other related services.
Hopefully nothing!  Unit tests have been added that cover the new functionality as well as the existing functionality, ensuring that all the services are registered as expected, and the typed service client can properly be resolved.
**Please check if the PR …
> Added methods to support creating RefitSettings using the service provider

- Refit.Tests/RequestBuilder.cs
- Refit/RestMethodInfo.cs
This is a bug fix for `HeaderCollection` and `Property` not working correctly on `Put` `Post` and `Patch` when no `[Body]` attribute is present.
The original bug was filed here https://github.com/reactiveui/refit/issues/1102 - essentially when no `[Body]` attribute is present Refit tries to infer a body using a parameter with a value type that is not of type `string` and is not marked with a `[Query]` attribute. The bug was caused by not adding `[HeaderCollection]` and `[Property]` attributes to that list in the original PR and not having sufficient test coverage for those Put/Post/Patch.
The `[HeaderCollection]` and `[Property]` attributes behave correctly on `Put` `Post` and …
> Header collection post without body bug

- README.md
Documentation update.
N/A
N/A
N/A
> Small typos in README

- README.md
- Refit.Tests/ResponseTests.cs
- Refit/RequestBuilderImplementation.cs
This is a bug fix for #1160 and #1017 - ApiResponse<T> wasn't trapping exceptions that occurred while attempting to deserialize the response, which violated the expectations of the ApiResponse<T> programming model.
The current behavior is that an ApiResponse<T> will throw a Refit.ApiException if an exception is thrown while attempting to deserialize the response.
The deserialization exception is properly wrapped by a Refit.ApiException and returned in the ApiResponse<T>
I've added tests for this and ensured the existing tests for the non ApiResponse<T> case still pass. If callers knew about the current behavior and had explicit try/catch blocks …
> Support returning api response in case of deserialization exception

- Refit.Tests/App.config
- Refit.Tests/InterfaceStubGenerator.cs
- Refit.Tests/Refit.Tests.csproj
- Refit.Tests/RequestBuilder.cs
- azure-pipelines.yml
Update to .NET 6 SDK
Add tests for #1211
> .NET 6 SDK update

- Refit/Refit.csproj
- Refit/targets/refit.props
@Mike-E-angelo I'm hoping we can use something like this PR to avoid needing to move these files completely outside the `analyzers` folder.
Fixes https://github.com/reactiveui/refit/pull/1216#issuecomment-902132236
> Change folder path to avoid implicit NuGet inclusions

- Refit/targets/refit.props
Addresses the issue described in https://github.com/reactiveui/refit/pull/1222#issuecomment-904768658.
This restriction can be removed once https://github.com/dotnet/roslyn/issues/55848 is resolved.
> Gate the incremental source generators on LangVersion=preview

- Refit/SystemTextJsonContentSerializer.cs
This is a new feature that extends/enhances SystemTextJsonContentSerializer initialization.
To enchance a default SystemTextJsonContentSerializer behavior (e.g. add/remove converters) it is required to create a new JsonSerializerOptions instance and initialize it the same way it is initialized in SystemTextJsonContentSerializer constructor (copy/pasting), then additional options can be added.
A user can create a JsonSerializerOptions initialized with defaults by calling `SystemTextJsonContentSerializer.GetDefaultJsonSerializerOptions()` extend it and use for SystemTextJsonContentSerializer initialization.
Not a breaking change.
**Please check if the …
> Enchance SystemTextJsonContentSerializer default options

- README.md
- Refit.Tests/ResponseTests.cs
- Refit/RestMethodInfo.cs
Bug fix
Refit interface methods that return `Task<IApiResponse>` _throw_ `ApiException` on error, rather than assigning it to the `IApiResponse.Error` property (like what happens for `Task<IApiResponse<T>>` or `Task<ApiResponse<T>>`). See #1289 for more details.
Refit interface methods that return `Task<IApiResponse>` will assign `ApiException` to the `IApiResponse.Error` property on error rather than throw it.
Consumers that rely on the old undocumented behavior of `ApiException` being thrown from Refit interface methods that return `Task<IApiResponse>`.
> Refit interface methods that return Task<IApiResponse> assign ApiException to the IApiResponse.Error property on error

- Refit/ApiException.cs
- Refit/ApiResponse.cs
- Refit/Attributes.cs
- Refit/MultipartItem.cs
- Refit/RefitSettings.cs
- Refit/RestService.cs
- Refit/XmlContentSerializer.cs
Xml Docs on publicly exposed classes and methods.
Most of the classes and methods you would use when using Refit have no Xml docs. Related issue: https://github.com/reactiveui/refit/issues/1274
Developers using the library will now see comments when typing a class or method name, hovering over them, etc.
I can't see how adding comments could break something so nothing afaik.
Let me know if I have missed something or if you see a comment that should be worded differently/is wrong !
> Add Xml documentation to exposed methods and classes.

- README.md
Docs update
TOC link to "When returning Task<IApiResponse>, Task<IApiResponse<T>>, or Task<ApiResponse<T>>" section is broken
TOC link to said section is restored
Nothing
> Update renamed section in Table of Contents

- Refit.Tests/RestService.cs
- Refit/RequestBuilderImplementation.cs
It fixes another code path related to the bug detailed in #1099.
When a Refit interface method returns `Task` rather than `Task<T>`, the `[Body(buffered: true)]` attribute is ignored.
Now void return interface methods will correctly buffer body content when specified in the Refit interface method signature.
It could break how POST/PUT bodies are serialized in requests.
> fix: load content into buffer for void return methods

- Refit/ApiResponse.cs
Improve support for nullable reference types.
See [this github issue](https://github.com/reactiveui/refit/issues/1302) for more details
Improved support for nullable reference types.
If it is possible for `Content` to be null when  `IsSuccessStatusCode == true`  or if  it is possible for `Error` to be null when `IsSuccessStatusCode` == false, this can lead to the compiler to believe the property is not null while in reality it is.
- [ N/A ] Tests for the changes have been added (for bug fixes / features)
- [ N/A ] Docs have been added / updated (for bug fixes / features)
I …
> Add MemberNotNullWhen attribute to IsSuccessStatusCode

- README.md
A bug report came in via an old issue https://github.com/reactiveui/refit/issues/801 that highlighted a bug in the docs. I've fixed the doc bug and added some guidance on how better to support a common use case and outlined in what case it's appropriate to pass the `Polly.Context` via the `[Property]` attribute.
see https://github.com/reactiveui/refit/issues/801 
Docs are fixed :)
Nothing - it's only updating documentation.
> Fixed a bug in the readme

- Refit.HttpClientFactory/HttpClientFactoryExtensions.cs
- Refit.HttpClientFactory/IRefitHttpClientFactory.cs
- Refit.HttpClientFactory/RefitHttpClientFactory.cs
Makes it possible to set a custom name to the HTTP Client factory
You can't use the same interface to point at multiple environments for example.
You can use custom names to the same interface but with different environment/handlers.
In the original implementation `UniqueName.ForType<T>()` was used as the client's name, so if a custom name is used it might break somewhere, tho I've looked and not found any other references for this other than tests.
> Adds named httpclient support

- Refit.Tests/RequestBuilder.cs
- Refit/HttpRequestMessageProperties.cs
- Refit/RequestBuilderImplementation.cs
Feature
No RestMethodInfo is available in the HttpMessageHandler
RestMethodInfo is now available in the HttpMessageHandler. Parameter-Name: `RestMethodInfo { get; } = "Refit.RestMethodInfo";`
Nothing
> Add RestMethodInfo in HttpRequestMessage (Options or Properties)

- Refit.Tests/ResponseTests.cs
- Refit/ApiResponse.cs
Bug fix
See https://github.com/reactiveui/refit/issues/1376
Fixes #1376
> Use Error property when throwing exception

- README.md
- Refit.HttpClientFactory/HttpClientFactoryExtensions.cs
- Refit.Tests/AuthenticatedClientHandlerTests.cs
- Refit/RefitSettings.cs
- Refit/RestService.cs
In order to maintain backwards compatibility, we now are ending up with three separate fetchers that do the same thing. Let's instead simplify since we're doing a breaking change anyways, and that this will be pretty straightforward for developers to deal with
API design change
Three separate properties to configure the same thing
One property for the same thing
Developers will need some find-replaces to fix it
> BREAKING: Simplify authorization configuration

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit.Tests/InterfaceStubGenerator.cs
- Refit.Tests/RestService.cs
Enhancement
`ApiException` call stack starts with something like:
```text
at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext()
```
`ApiException` call stack starts with something like:
```text
at Refit.Implementation.Generated.RefitTestsIGitHubApi.<global::Refit-Tests-IGitHubApi-CreateUser>d__29.MoveNext()
```
Useful for observability to know which request method failed.
Folks that depend on the existing stack trace.
👋
> Rethrow for Better Stack Trace

- README.md
docs update
See #1403
Clearly documented
documentation only.  Helps devs get started more easily with Auth in Refit.
* Addressing #1403
> Document InnerHandler null requirement for DI

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
This PR introduces a code formatting change. It reformats the code to improve its readability by adjusting the indentation of the LINQ query, making it more consistent with coding standards.
The current behavior of the code is that it uses inconsistent indentation in the LINQ query.
The new behavior of the code is that it uses consistent and improved indentation in the LINQ query, making it more readable and aligned with coding standards.
This PR is unlikely to break any functionality or introduce bugs since it focuses on code formatting changes that do not affect the logic or behavior of the code.
**Please check if the PR fulfills these …
> refactor: Refactor code formatting for better readability

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit.Tests/InterfaceStubGenerator.cs
Use `Array.Empty` over allocating an empty array where possible. Done for `______arguments` and `parameterTypes`..
See #1598
> feat: generate code that uses `Array.Empty` where possible

- Refit/FormValueMultimap.cs
- Refit/RequestBuilderImplementation.cs
Splitting up #1596, tried to avoid modifying the whitespace.
- use `TryGetValue` over `ContainsKey`/lookup
- Remove unneeded array duplication via `ToArray`
- Invert ifs to improve readability
> chore: minor refactors

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit.Tests/InterfaceStubGenerator.cs
Removed a generated chunk of whitespace from `InterfaceStubGeneratorV2` and updated the corresponding tests.
Super nitpicky but it was causing issues with my editor when adding an incremental generator.
> chore: remove generated whitespace

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit.Tests/InterfaceStubGenerator.cs
Modify source generator to use `private static readonly` fields to store the `typeParameter` arrays, saving the allocations for each request.
- Only generates when there are actual arguments, otherwise `Array.Empty` is used - #1599
- `private static` fields are generated beside its respective method, this could be moved to the start of the class if requested.
- I've used a `HashSet` of each member in scope to accidental name collisions. Fields will have names like `_typeParameters3` incrementing for each field generated. 
- ~Uses nullable coalescing assignment if one of the method parameters uses type arguments. This is done as we may not be able to access it from outside the method scope making the array initialization invalid.~
- ~It should be safe to initialize and set the static …
> feat: use `private static` fields to store constant `typeParameters` where possible

- Refit/RequestBuilderImplementation.cs
- changed `ToList` to `ToArray` - attempted to refactor the method to not create closures but it didn't make an impact on memory usage 🤷 
- use `TryGetValue`
- Refactor `DoNotConvertToQueryMap` made `ShouldReturn` static and removed unneeded calls to it
Follow up to #1619
>  chore: minor refactor

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit.Tests/InterfaceStubGenerator.cs
Added leading underscores to `typeParameter` to be inline with the other variables (`______arguments` and `______func`).
Should prevent a scenario where the name is already used in the interface.
> feat: add leading underscores to `typeParameter` name

- Refit/Refit.csproj
update
Packages are the same for all TFM's
Less dependencies are included for net 6+ due to them being available as part of the framework
n/a
closes #1684
> #1684 Tweak Dependencies

- Refit.HttpClientFactory/Refit.HttpClientFactory.csproj
- Refit.Newtonsoft.Json/Refit.Newtonsoft.Json.csproj
- Refit.Tests/Refit.Tests.csproj
- Refit.Tests/Verifiers/CSharpIncrementalSourceGeneratorVerifier`1+Test.cs
- Refit.Tests/Verifiers/CSharpSourceGeneratorVerifier`1+Test.cs
- Refit.Xml/Refit.Xml.csproj
- Refit/Refit.csproj
Feature
Tested up to DotNet 7
Tested up to DotNet 8
DotNet 6+ targets have been changed to NetStandard 2.1 to allow the support for DotNet 8
> Feature Add DotNet 8 support

- Refit/ApiResponse.cs
Potential fix for https://github.com/reactiveui/refit/issues/1671
An alternative way:
`new bool IsSuccessStatusCode { get; }` property in the `IApiResponse<T>` interface with all 3 attributes above
> Issue 1671: Add MemberNotNullWhen attribute for Content property in IApiResponse<T>

- Refit/ApiResponse.cs
update
The ApiResponse was adjusted but the implementation was misunderstood
The ApiResponse has been updated, a Live test is required for this with a net 8.0 target due to the nature of operation.
None
> Update ApiResponse to correct previous adjustment

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit.Tests/InterfaceStubGenerator.cs
This is an implementation complement to #1389, which enables `Generated.g` codes to be preserved during trimming, thereby supporting AOT publish of .NET 7.0 or later versions.This implementation has been used in the [WebApiClient](https://github.com/dotnetcore/WebApiClient) project and is valid for .NET versions 5.0 to 9.0 and is safe.
`<TrimMode>full</TrimMode>` is the default behavior of .NET8. Once `<PublishAot>true</PublishAot>` is turned on, all the code currently generated in `Generated.g` will be trimmed, causing AOT publishing to fail.
Cleverly use [ModuleInitializerAttribute](https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/proposals/csharp-9.0/module-i …
> .NET7.0+ AOT supported

- Refit/RequestBuilderImplementation.cs
- Remove unused using statements
- Invert ifs
- Use `TryGetValue`
- Remove unneeded `ToArray`
- Make local function static
Reverts changes made in #1570
I can't guarantee that I've caught everything. Future PR needs to rerun csharpier
> feat: refactor, invert ifs, use optimal methods

- Refit.Benchmarks/EndToEndBenchmark.cs
- Refit.Benchmarks/IGitHubService.cs
- Refit.Benchmarks/IPerformanceApi.cs
- Refit.Benchmarks/IPerformanceService.cs
- Refit.Benchmarks/PerformanceBenchmark.cs
- Refit.Benchmarks/Program.cs
- Refit.Benchmarks/StartupBenchmark.cs
- Refit.Benchmarks/StaticFileHttpResponseHandler.cs
- Refit.Benchmarks/StaticValueHttpResponseHandler.cs
- Used file scoped namespaces and simplified `Program.cs`
- Added `PerformanceBenchmark` to measure the speed to create and make the average request.
- `StartupBenchmark` measures Refit api creation and call time.
- Measures: Service creation time, service creation and first call, just first call.
- Not sure if its worth having the first call benchmarks as they have contradictory results. Why does `FirstCallComplexRequestAsync` use less memory than repeated calls? I might be missing something.
| Method                   | Mean      | Error     | StdDev    | Gen0   | Gen1   | Allocated |
|------------------------- |----------:|----------:|----------:|-------:|-------:|----------:|
| ConstantRouteAsync       |  2.940 us | 0.0587 us | 0.0897 us | 0.7744 | 0.0038 |   7.13 KB |
| …
> feat: add startup and performance benchmarks

- Refit/RequestBuilderImplementation.cs
- Refit/ValueStringBuilder.cs
Uses [`ValueStringBuilder`](https://github.dev/dotnet/runtime/blob/main/src/libraries/Common/src/System/Text/ValueStringBuilder.cs) to generate query parameters for the uri and prepend a question mark.
Update: turns out `UriBuilder` has been changed between .NET Framework and Core. Core checks for leading `?` symbols whereas Framework always adds one. I've added a preprocessor directive to resovle this issue.
| Method                     | Mean     | Error    | StdDev   | Gen0   | Gen1   | Allocated |
|--------------------------- |---------:|---------:|---------:|-------:|-------:|----------:|
| TaskTQueryLong_Async       | 12.97 us | 0.258 us | 0.665 us | 1.5717 | 0.0458 |  14.45 KB |
| TaskTCollectionQuery_Async | 18.64 us | 0.372 us | 0.848 us | 1.8921 | 0.0610 |   17.4 KB |
| Method …
> feat: use `ValueStringBuilder` adding the query parameters

- Refit/Attributes.cs
- version.json
Fix For #1733
Accidental sealing of Attributes made
Reverted to unsealed, added note to ensure unsealed attributed are not sealed again.
Reverting of previous functionality.
> Revert sealed Attributes

- Refit.Tests/CachedRequestBuilder.cs
- Refit/CachedRequestBuilderImplementation.cs
Rewrote `CachedRequestBuilder` to use a custom `MethodTableKey` value as a dictionary key instead of a concatenated string. Resulted in some modest memory savings and reduced object usage.
- Added unit tests to ensure that the dictionary key works correctly.
- On lines 48 & 49 of `CachedRequestBuilderImplementation` I copy the arrays to create the dictionary key, this is to prevent the arrays being changed, breaking the dictionary. This can be removed if Refit assumes that the input arrays are not accessible to the user.
- Implemented `IEquatable<MethodTableKey>`, implementing my own `GetHashCode` method. I could have used the recommended `HashCode` object but it is not available in .NET Framework. I could copy the implementation over and use it if you want.
| Method             | Mean …
> feat: optimize `CachedRequestBuilder`

- Refit.Benchmarks/Program.cs
- Refit/EnumerableExtensions.cs
- Refit/RestMethodInfo.cs
- Added `TryGetSingle` to get the first value of an enumerable and determine the size.
- Replaced `ToList` with `TryGetSingle` where possible
- Converted `parameterList` to `parameterArray`
- Fixed a typo in `Benchmarks.Program`
Overall saved 1.5KB on startup
| Method                       | Job        | InvocationCount | UnrollFactor | Mean      | Error     | StdDev    | Median    | Gen0   | Gen1   | Allocated |
|----------------------------- |----------- |---------------- |------------- |----------:|----------:|----------:|----------:|-------:|-------:|----------:|
| CreateService                | DefaultJob | Default         | 16           | 50.549 us | 0.4770 us | 1.1055 us | 50.153 us | 5.2490 | 0.1221 |  48.44 KB |
| ConstantRouteAsync           | DefaultJob | Default         | 16 …
> feat: use `TryGetSingle` instead of collection enumerable to lists.

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit.Tests/InheritedInterfacesApi.cs
- Refit.Tests/InterfaceStubGenerator.cs
closes #1724
ex is used within the generated code, this is a common name
Updated ex to be refit_ex to minimise the likelihood that there will be conflict.
None expected due to new name
> Fix for Common Parameter Name used in Generated code

- Refit.Tests/RequestBuilder.cs
- Refit/RequestBuilderImplementation.cs
Closes #1732 
Fixes a bug where existing query parameters would have their positions reversed #1732
- Extracted logic into a method
- If the existing `Query` is empty we early return
- This early return prevents the allocation of an empty 300 byte `NameValueCollection`
- Otherwise the query is parsed with each key pair added
- There might be room for improvement here by using a linq `Select` method. `Select` would know the length of the collection and `InsertRange` would be able to bulk copy the values. This could only be done if we know for certain that the key can't be empty and `Where` is not required.
| Method                   | Mean      | Error     | StdDev    | Gen0   | Gen1   | Allocated |
|------------------------- |----------:|----------:|----------:|-------:|-------:|---------- …
> feat: fix existing query values bug

- Refit/RequestBuilderImplementation.cs
Extracted methods into:
- `AddBodyToRequest`
- `AddQueryParameters`
- `AddMultiPart`
- `AddHeadersToRequest`
- `AddPropertiesToRequest`
I haven't changed any logic, this commit is to make it easier to understand the scope of logic and to cut down on the massive function. I plan on removing the following collections in a subsequent pr 🤞 
```c#
var queryParamsToAdd = new List<KeyValuePair<string, string?>>(); // either use `ValueStringBuilder` or `ValueListBuilder`
var headersToAdd = new Dictionary<string, string?>(restMethod.Headers); `ValueListBuilder` or add directly with a check
var propertiesToAdd = new Dictionary<string, object?>(); // iterate params later on and directly add to `HttpRequest` both property/option are internally dictionaries.
```
> chore: extract methods

- Refit/RequestBuilderImplementation.cs
- Relies on #1740
- `Options` and `Properties` both internally use dictionaries so `propertiesToAdd ` isn't needed
- When iterating parameters, refit now checks if `PropertyParameterMap` contains the key and sets `isParameterMappedToRequest` to be true.
- `AddPropertiesToRequest` iterates the parameter indices, adding them to `Options`/`Properties` if they are in `AddPropertiesToRequest`
Small memory saving of 72 bytes, the size of an empty `Dictionary`. These benefits are much greater when a property is used.
| Method                   | Mean      | Error     | StdDev    | Gen0   | Gen1   | Allocated |
|------------------------- |----------:|----------:|----------:|-------:|-------:|----------:|
| ConstantRouteAsync       |  2.576 us | 0.0511 us | 0.0699 us | 0.7553 |      - |   6.95 KB …
> feat: remove properties dictionary

- Refit/RequestBuilderImplementation.cs
Defer header dictionary creation, saves 72 bytes if a header is not set.
| Method                   | Mean      | Error     | StdDev    | Gen0   | Gen1   | Allocated |
|------------------------- |----------:|----------:|----------:|-------:|-------:|----------:|
| ConstantRouteAsync       |  2.032 us | 0.0223 us | 0.0209 us | 0.6905 |      - |   6.36 KB |
| DynamicRouteAsync        |  2.626 us | 0.0186 us | 0.0165 us | 0.7248 | 0.0038 |   6.68 KB |
| ComplexDynamicRouteAsync |  3.825 us | 0.0197 us | 0.0175 us | 0.7935 | 0.0076 |   7.31 KB |
| ObjectRequestAsync       |  4.470 us | 0.0250 us | 0.0234 us | 0.8774 |      - |   8.13 KB |
| ComplexRequestAsync      | 12.379 us | 0.0479 us | 0.0448 us | 1.5411 | 0.0153 |  14.19 KB |
| Method                   | Mean      | Error     | StdDev …
> feat: defer header dictionary creation

- Refit.Tests/RequestBuilder.cs
- Refit/FormValueMultimap.cs
Add check for strings to form url encoded requests. This way strings aren't serialized as collections. Added relevant test.
Fixes #1593
> feat: fix form url encoded strings #1593

- Refit/RequestBuilderImplementation.cs
- Extract logic for parameter mapping to `AddObjectParametersToUrl` and `AddValueParameterToUrl`
- Small formatting fixes
Final bit of #1740 because I can't get #1730 to work 😄
> feat: extract logic and small cleanups

- Refit.GeneratorTests/Fixture.cs
- Refit.GeneratorTests/ModuleInitializer.cs
- Refit.GeneratorTests/Refit.GeneratorTests.csproj
- Refit.GeneratorTests/ReturnTypeTests.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.GenericTaskShouldWork#Generated.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.GenericTaskShouldWork#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.GenericTaskShouldWork#PreserveAttribute.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.VoidTaskShouldWork#Generated.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.VoidTaskShouldWork#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.VoidTaskShouldWork#PreserveAttribute.g.verified.cs
- Refit.sln
Redo of #1753, this time focusing on individual cases.
- Added some basic tests.
- I intend to keep `InterfaceStubGenerator` in the main tests to target the latest version of .NET framework if possible. I'm trying not to use unsafe code in a rewrite, but if I do .NET Framework will have to be handled uniquely.
- Using this in my source generator rewrite, I'm trying to split it into smaller PRs so I don't dump a massive change on you.
- Got a pr with `Verify.SourceGenerator` to add a way to ignore certain files. I'd like to use it on the duplicate `PreserveAttribute.cs` files.
> feat: added generator tests

- Directory.Build.props
- Refit.GeneratorTests/Refit.GeneratorTests.csproj
- Refit.GeneratorTests/ReturnTypeTests.cs
- Refit.Tests/API/ApiApprovalTests.Refit.DotNet6_0.verified.txt
- Refit.Tests/API/ApiApprovalTests.Refit.DotNet8_0.verified.txt
- Refit/ApiException.cs
- version.json
It adds the MemberNotNullWhen annotation to the Content / HasContent pair in ApiException.
VS does not recognize `Content` being non-null when `HasContent` is `true`.
VS should recognize `Content` being non-null when `HasContent` is `true`.
> Add MemberNotNullWhen annotation for Content / HasContent pair

- Refit.Tests/API/ApiApprovalTests.Refit.DotNet6_0.verified.txt
- Refit.Tests/API/ApiApprovalTests.Refit.DotNet8_0.verified.txt
- Refit.Tests/DefaultUrlParameterFormatterTest.cs
- Refit.Tests/DefaultUrlParameterFormatterTests.cs
- Refit/RefitSettings.cs
Closes #1775 
This PR extends the `DefaultUrlParameterFormatter` with additional formatting options based on parameter type or a combination of request and parameter types. This allows values with no `QueryAttribute` format to be custom-formatted without the necessity of fully reimplementing `DefaultUrlParameterFormatter`.
**Example usage:**
```c#
class CustomUrlParameterFormatter : DefaultUrlParameterFormatter
{
public CustomUrlParameterFormatter()
{
AddFormat<DateTime>("yyyy-MM-ddTHH:mm:ss");
AddFormat<MyRequest, DateTime>("yyyy-MM-ddTHH:mm:ss.fffZ");
}
}
```
or
```c#
var urlParameterFormatter = new DefaultUrlParameterFormatter();
urlParameterFormatter.AddFormat<DateTime>("yyyy-MM-ddTHH:mm:ss");
urlParameterFormatter.AddFormat<MyRequest, DateTime>("yyyy-MM-ddTHH:mm:ss.fffZ");
``` …
> Extend url parameters default formatting

- README.md
Readme update regarding JSON Source Generator
JsonSerializerOptions.AddContext is obsolete. (https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.addcontext?view=net-8.0)
> Update README.md JSON Source Generator

- Refit.Benchmarks/Program.cs
- Refit.Benchmarks/Refit.Benchmarks.csproj
- Refit.Benchmarks/SourceGeneratorBenchmark.cs
Added benchmarks for source generation.
Assuming these benchmarks are valid, the results show a very small benefit from caching.
| Method  | Mean     | Error   | StdDev  | Gen0    | Gen1   | Allocated |
|-------- |---------:|--------:|--------:|--------:|-------:|----------:|
| Compile | 225.9 us | 3.34 us | 2.96 us | 13.1836 | 2.9297 | 124.09 KB |
| Cached  | 196.7 us | 3.37 us | 2.99 us | 13.1836 | 2.9297 | 122.19 KB |
| Method  | Mean     | Error   | StdDev  | Median   | Gen0    | Gen1   | Allocated |
|-------- |---------:|--------:|--------:|---------:|--------:|-------:|----------:|
| Compile | 225.0 us | 4.42 us | 9.22 us | 221.2 us | 13.1836 | 2.9297 | 124.09 KB |
| Cached  | 197.6 us | 2.77 us | 2.59 us | 197.0 us | 13.1836 | 2.9297 | 122.18 KB |
| Method  | Mean     | Error   | …
> feat: added source generator benchmarks

- Refit.GeneratorTests/Fixture.cs
- Refit.GeneratorTests/InterfaceTests.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.ContainedInterfaceTest#Generated.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.ContainedInterfaceTest#IContainedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.ContainedInterfaceTest#PreserveAttribute.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.DerivedNonRefitInterfaceTest#Generated.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.DerivedNonRefitInterfaceTest#IGeneratedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.DerivedNonRefitInterfaceTest#PreserveAttribute.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.DerivedRefitInterfaceTest#Generated.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.DerivedRefitInterfaceTest#IBaseInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.DerivedRefitInterfaceTest#IGeneratedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.DerivedRefitInterfaceTest#PreserveAttribute.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.GlobalNamespaceTest#Generated.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.GlobalNamespaceTest#IGeneratedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.GlobalNamespaceTest#PreserveAttribute.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.NestedNamespaceTest#Generated.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.NestedNamespaceTest#IGeneratedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.NestedNamespaceTest#PreserveAttribute.g.verified.cs
Added interface snapshot tests. In preparation for #1791
- Updated `Fixture` to support custom type and namespace tests.
- Added tests for:
- Derived scenarios
- Nested/global namespaces
- Inner interfaces
Discovered #1801
> feat: added interface snapshot `InterfaceTests`

- Refit/Refit.csproj
closes #1782 
A dependency exists for System.Net.Http.Json, this has a dependency on System.Text.Json which has a vulnerability.
Removing System.Net.Http.Json from Net 6+ will ensure that the current Net6.0.x or Net8.0.x assemblies will be used
None
> Remove Dependency System.Net.Http.Json from Net 6+

- InterfaceStubGenerator.Roslyn38/InterfaceStubGenerator.Roslyn38.csproj
- InterfaceStubGenerator.Roslyn40/InterfaceStubGenerator.Roslyn40.csproj
Fix for #1817 by reverting 29e0e1c. Not sure if `Microsoft.CodeAnalysis.CSharp` was intentionally updated to the latest versions, guessing it broke the source generator for anyone on an older ide.
> feat: revert 29e0e1c

- Directory.Build.props
- InterfaceStubGenerator.Roslyn38/InterfaceStubGenerator.Roslyn38.csproj
- InterfaceStubGenerator.Roslyn40/InterfaceStubGenerator.Roslyn40.csproj
- Refit.HttpClientFactory/Refit.HttpClientFactory.csproj
- Refit.Newtonsoft.Json/Refit.Newtonsoft.Json.csproj
- Refit.Xml/Refit.Xml.csproj
- Refit/Refit.csproj
- version.json
Update for Release of bug fixes.
> Housekeeping Update Version

- Refit/Refit.csproj
fix
closes #1552
Contains a reference that has no useage
The reference to System.Net.Http has been removed
Not expected unless the System.Net.Http lib is being relied upon by end user for their own code.
> Fix for unused reference System.Net.Http

- Refit.Tests/AuthenticatedClientHandlerTests.cs
- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
Fix
Header and Authorise attributes could CRLF which may cause issues
Added detection and correction of CRLF characters.
None expected
> Fix to disable Header and Authorise attributes containing CRLF

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
- Refit.GeneratorTests/_snapshots/GeneratedTest.ShouldEmitAllFiles#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.ContainedInterfaceTest#IContainedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.GlobalNamespaceTest#IGeneratedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.InterfaceDerivedFromRefitBaseTest#IBaseInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.InterfaceDerivedFromRefitBaseTest#IDerivedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.NestedNamespaceTest#IGeneratedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.RefitInterfaceDerivedFromBaseTest#IGeneratedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.RefitInterfaceDerivedFromRefitBaseTest#IBaseInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.RefitInterfaceDerivedFromRefitBaseTest#IGeneratedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.GenericTaskShouldWork#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.VoidTaskShouldWork#IGeneratedClient.g.verified.cs
- Refit.Tests/InterfaceStubGenerator.cs
- Refit.Tests/RestService.cs
Bug fix
Fixes #1809
Currently there is a try/catch block surrounding the api call which rethrows the exception causing the stack trace to be discarded. 
As the try catch block was not doing anything specific, it seemed better to remove it completely and have the original exception be thrown.
Not sure - different type of exceptions?
> Remove unnecessary try/catch block as to not lose the stack trace

- InterfaceStubGenerator.Shared/DiagnosticDescriptors.cs
- InterfaceStubGenerator.Shared/InterfaceStubGenerator.Shared.projitems
- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
Refactor: move diagnostics descriptors to separate file
- Will use `InternalsVisibleTo` to expose descriptors for future #1829 changes.
- Ideally refit could do with some more descriptors, this should be a future PR
> refactor: move diagnostics to dedicated class

- Refit.GeneratorTests/GeneratedTest.cs
- Added test to verify that the generator does not emit any code when no valid refit interfaces are present.
- Verifies that line 169 in `InterfaceStubGenerator` functions.
Added to prevent me breaking this in #1791
> feat: add `ShouldNotEmitFiles` test

- Refit.Benchmarks/SourceGeneratorBenchmark.cs
- Refit.Benchmarks/SourceGeneratorBenchmarksProjects.cs
- Added benchmark for larger projects (`SmallInterface` copied 100 times).
- Moved the project text to a dedicated class.
- Kept it "small" so benchmarks will run under 2 minutes.
| Method      | Mean       | Error    | StdDev   | Gen0     | Gen1     | Allocated  |
|------------ |-----------:|---------:|---------:|---------:|---------:|-----------:|
| Compile     |   250.0 us |  2.03 us |  1.80 us |  12.6953 |   2.9297 |  117.52 KB |
| Cached      |   217.7 us |  3.63 us |  4.04 us |  12.2070 |   2.9297 |  114.87 KB |
| CompileMany | 8,920.5 us | 36.61 us | 34.24 us | 687.5000 | 343.7500 | 6354.55 KB |
| CachedMany  | 7,919.1 us | 57.02 us | 47.61 us | 671.8750 | 328.1250 | 6289.47 KB |
#1791
> feat: added larger benchmark

- Refit.GeneratorTests/InterfaceTests.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.NonRefitMethodShouldRaiseDiagnostic#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.NonRefitMethodShouldRaiseDiagnostic.verified.txt
Add test to ensure that non refit methods generate `NotImplementedException` and raise a diagnostic
> feat: add non refit method raises diagnostic test

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs
When writing a generic contraint for types constrained to `unmanaged`, Refit will incorrectly emit the invalid syntax `unmanaged struct`.
This is because types constrained with `unmanaged` are implicitly `struct` types meaning that both `HasValueTypeConstraint` and `HasUnmanagedTypeConstraint` will return true, emitting the invalid code.
Related #1859
> feat: fix invalid `unmanaged struct` constraint generation

- README.md
- Refit.Tests/DeserializationExceptionFactoryTests.cs
- Refit/RefitSettings.cs
- Refit/RequestBuilderImplementation.cs
feature described here: https://github.com/reactiveui/refit/issues/1815
there is no way to suppress or override deserialization exceptions
provides the option to suppress or override deserialization exceptions
no breaking changes
- [ X ] Tests for the changes have been added (for bug fixes / features)
- [ X ] Docs have been added / updated (for bug fixes / features)
> custom exception factory for deserialization exceptions

- Refit.GeneratorTests/ParameterTests.cs
- Refit.GeneratorTests/ReturnTypeTests.cs
- Refit.GeneratorTests/_snapshots/ParameterTests.NullableRouteParameter#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/ParameterTests.NullableValueTypeRouteParameter#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/ParameterTests.RouteParameter#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/ParameterTests.ValueTypeRouteParameter#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.ReturnNullableObject#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.ReturnNullableValueType#IGeneratedClient.g.verified.cs
- Added nullable return type tests for nullable objects and value types
- Added route parameter tests for nullable objects and value types
> feat: added nullable and parameter tests

- Refit.GeneratorTests/MathodTests.cs
- Refit.GeneratorTests/_snapshots/MethodTests.MethodsWithGenericConstraints#IGeneratedClient.g.verified.cs
- Refit.GeneratorTests/_snapshots/MethodTests.MethodsWithGenericConstraints.verified.txt
Ensure that constraints are generated correctly for refit and non refit methods.
Related to #1864
> chore: added generic constrained method tests

- Refit.Tests/RestService.cs
Test documenting argument covariance behavious on path and queries.
See #1882
> feat: add derived type argument tests

- Refit.GeneratorTests/InterfaceTests.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.DefaultInterfaceMethod#IGeneratedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.DerivedDefaultInterfaceMethod#IBaseInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.DerivedDefaultInterfaceMethod#IGeneratedInterface.g.verified.cs
Added default interface method test, should catch any mistakes ie #1875 overriding DIMs.
Related #1801, #1875
> feat: add default interface method tests

- Refit.Tests/API/ApiApprovalTests.Refit.DotNet6_0.verified.txt
- Refit.Tests/API/ApiApprovalTests.Refit.DotNet8_0.verified.txt
- Refit/ApiResponse.cs
This is the second attempt to add `[MemberNotNullWhen]` attribute for `Content` property of `IApiResponse<T>`. 
Issue https://github.com/reactiveui/refit/issues/1671
Analyzer doesn't know that `Content` is not null if `IsSuccessStatusCode` is `true`.
Analyzer sees new attributes and doesn't show warning\error about possible null ref.
I hope nothing. 
- I had to add 3 `new` properties to the derived interface otherwise Rider shows the waring and analyzer ignores attribute for property, declared in the base interface. 
- Explicit base property implementation may lead to the unexpected behavior based on the resolved interface …
> Add workaround and missing `[MemberNotNullWhen]` attributes

- Refit.Tests/RestServiceExceptions.cs
Added tests to verify that `RestMethodInfo` throws an exception when invalid interfaces are initialized through `RestService.For`.
This duplicates tests found in `Refit.Tests/RequestBuilder` however these will have to deleted if I get round to removing `RequestBuilder` and all corresponding runtime logic
> feat: add `Tests/RestServiceExceptions`

- InterfaceStubGenerator.Shared/Parser.cs
- Refit.GeneratorTests/Incremental/InheritanceTest.cs
- Refit.GeneratorTests/InterfaceTests.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.RefitInterfaceDerivedFromBaseTest#IGeneratedInterface.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.RefitInterfaceDerivedFromBaseTest.verified.txt
- Refit.Tests/InheritedInterfacesApi.cs
- Refit.Tests/RestService.cs
Fixes #1801
- Raise diagnostics and create empty methods for derived non refit methods.
- Incomplete as [this comment](https://github.com/reactiveui/refit/issues/1801#issuecomment-2406124552) needs to be addressed.
@ChrisPulman do you have any guidance here? Is this PR blocking you from the next release.
> feat: generate code for derived non refit methods.

- Refit.Tests/ReflectionTests.cs
Add a reflection test to verify the types of `ICustomAttributeProvider` and `Type` arguments provided to `IUrlParameterFormatter.Format`.
This is to prevent me from breaking anything while I rewrite the generator to provide these values as fields at compile time.
> feat: add `ReflectionTests` for `IUrlParameterFormatter`

- Refit.Benchmarks/IPerformanceService.cs
- Refit.Benchmarks/PerformanceBenchmark.cs
- Refit.Benchmarks/StartupBenchmark.cs
Change return types from `Task<string>` to `Task<HttpResponseMessage`. This makes the benchmarks more accurate as they are intended to measure the cost of configuring and sending a `HttpRequestMessage` and not the time taken to convert the response into a `string`.
On a related note why isn't refit using `ReadAsStringAsync`?
| Method                   | Mean      | Error     | StdDev    | Gen0   | Allocated |
|------------------------- |----------:|----------:|----------:|-------:|----------:|
| ConstantRouteAsync       |  2.072 us | 0.0110 us | 0.0097 us | 0.2937 |   2.71 KB |
| DynamicRouteAsync        |  2.783 us | 0.0259 us | 0.0202 us | 0.3319 |   3.07 KB |
| ComplexDynamicRouteAsync |  4.060 us | 0.0226 us | 0.0200 us | 0.4044 |   3.78 KB |
| ObjectRequestAsync       |  4.954 us | …
> feat: change `IPerformanceService` to return `HttpResponseMessage`

- InterfaceStubGenerator.Shared/Emitter.cs
- InterfaceStubGenerator.Shared/InterfaceStubGenerator.Shared.projitems
- InterfaceStubGenerator.Shared/UniqueNameBuilder.cs
- Added `UniqueNameBuilder`
- Used to create unique names within scopes.
Breaking up my source gen pr.
> feat: add `UniqueNameBuilder`

- Refit.Tests/RestServiceExceptions.cs
Having another crack at #1730, so I'm preemptively adding tests
> feat: add parameter substitution tests

- README.md
- version.json
> Prepare For Release of V8.0.0

- Refit.Tests/RestService.cs
Add url query tests, checks for whitespace, empty values, weird characters and escaped/non-escaped values
> feat: add url query tests for `Refit.Tests/RestService`

- Refit.Tests/RestService.cs
- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
Parse the url target inside `RestMethodInfo`, removing the use of regex on function calls.
Re attempt at #1730. Turns out the additional allocations were caused by [line 829](https://github.com/TimothyMakkison/refict/blob/94bf0a5f521e0ae8dc57e11cd2eb475ff9e003d6/Refit/RequestBuilderImplementation.cs#L829) creating a closure. Looking at the lowered code C# always created the linq closure, even when round tripping was never used 🤔 
In future I could optimise round trip to not use `string.Split`, either manually splitting or using `Span.Split`
| Method                   | Mean      | Error     | StdDev    | Median    | Gen0   | Allocated |
|------------------------- |----------:|----------:|----------:|----------:|-------:|----------:|
| ConstantRouteAsync       |  9.332 us | 0.6444 us | …
> feat: calculate path substitutions in `RestMethodInfo`

- Refit.Tests/RestService.cs
- Refit.Tests/RestServiceExceptions.cs
- Added fragment tests, ensuring that the fragment is always removed. ie `/foo#name` -> `/foo`
- Updated `InvalidParamSubstitutionShouldThrow`
- Added `InvalidFragmentParamSubstitutionShouldThrow` 
This is to prevent future changes to Uri from breaking things. I'm looking at removing `Uri` and `UriBuilder` creation in [RequestBuilderImplementation.](https://github.com/reactiveui/refit/blob/961984118885db34c39d8b4eb2a326786c560e71/Refit/RequestBuilderImplementation.cs#L761)
Out of curiosity why doesn't refit support fragments, is this intentional or an oversight?
> feat: add URL fragment tests

- Refit/RequestBuilderImplementation.cs
Lazy initializes `List<KeyValuePair<string, string?>> queryParamsToAdd` only when it is used.
- Saves 32 bytes for none query calls.
`AddQueryParameters` could be updated to not create interim lists and just directly update a given list. However, with a couple of changes refit could just directly write queries into a `ValueStringBuilder` representing the URL.
> feat: lazy initialize `queryParamsToAdd`

- Refit/RequestBuilderImplementation.cs
- Refit/RestMethodInfo.cs
- Converted the `string Name` property to an expression that returns `MethodInfo.Name`
- Removed unused setters from properties
- `AddProperties` will reuse the same `RestMethodInfo` object instead of creating a new one for each request, saving 56 bytes per request.
-  Is this used by consumers or is it only for testing?
- I could modify `RestMethodInfo` to contain a private pointer to the parent `RestMethodInfoInternal` and expose values as expression properties. This would save a couple of bytes for each use of `RestMethodInfoInternal` but would change the public constructor.
> feat: cache `RestMethodInfo`

- Refit.Tests/HttpClientFactoryExtensionsTests.cs
Adds a test to confirm and conform Refit.HttpClientFactory's AddRefitClient with respect to named HttpClients.
Fixes #1909
AddRefitClient can reuse existing named clients, but it can also reconfigure the named clients' factories.
No new behavior, just a test confirming that existing behavior is to pick up named clients.
Nothing
Docs could be updated further to make it clear that AddRefitClient will use named clients and that you will reconfigure the named client's factory if you use AddRefitClient's returned IHttpClientBuilder (as described in #1686).
> feat: test Named HttpClient reuse by AddRefitClient

- Refit.Tests/RestService.cs
Looks like `MockHttpMessageHandler.WithExactQueryString("&&&")` will always return true, even if there aren't `&` symbols.
> chore: delete broken test

- Refit.Tests/RestService.cs
- Refit/RestMethodInfo.cs
- Prevent `CancellationToken?` being serialized.
- Add cancellation tests to `Tests/RestService`, including `NullableCancellationTokenShouldBeIgnored` 
I'm not sure how Refit should handle nullable Cancellation token, it's a struct so it isn't nullable by default. My two ideas:
- Refit functions containing a `CancellationToken` parameter should throw an exception or emit a diagnostic.
- Accept `CancellationToken?`, check these tokens for nullability. If they are null then substitute it with a default token.
See #1915
> feat: prevent serialization of `CancellationToken?`

- InterfaceStubGenerator.Shared/Parser.cs
- Refit/UniqueName.cs
Replaces `-`/`@` with `_`. in `refitInternalNamespace`.
Do you know what characters csproj supports?
Fixes #1920
> fix: support - symbols in csproj names

- Refit.Tests/RestService.cs
- Refit/RequestBuilderImplementation.cs
- Add check in `ShouldReturn` for `Nullable<T>` types.
- Added test to `Tests/RestService`
Fixes #1568
> fix: support nullable value type collection in queries

- InterfaceStubGenerator.Shared/Parser.cs
- Refit.GeneratorTests/InterfaceTests.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.InterfacesWithDifferentCasing#IApi.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.InterfacesWithDifferentCasing#Iapi1.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.InterfacesWithDifferentSignature#IApi.g.verified.cs
- Refit.GeneratorTests/_snapshots/InterfaceTests.InterfacesWithDifferentSignature#IApi1.g.verified.cs
- Add `StringComparer.OrdinalIgnoreCase` to `keyCount`
- Added name casing test and same name, different signature test
Fixes #1689
> fix: support interfaces with different name casing

- InterfaceStubGenerator.Shared/InterfaceStubGenerator.Shared.projitems
- InterfaceStubGenerator.Shared/Models/WellKnownTypes.cs
- InterfaceStubGenerator.Shared/Parser.cs
Caches lookups to `Compilation` not very useful right now but will be needed for AOT. Should break up the final PR a tiny bit
> feat: added `WellKnownType`

- Refit.GeneratorTests/ReturnTypeTests.cs
- Refit.GeneratorTests/_snapshots/ReturnTypeTests.ReturnUnsupportedType#IGeneratedClient.g.verified.cs
Adds a generated code test for a refit method that does not have a `Task`/`IObservable` return type signature.
> test: add unsupported return type test

- Refit.Tests/GitHubApi.cs
- Refit.Tests/InterfaceStubGenerator.cs
- Refit.Tests/ModuleInitializer.cs
- Refit.Tests/ModuleInitializerAttribute.cs
- Refit.Tests/RestService.cs
- Refit.Tests/_snapshots/InterfaceStubGeneratorTests.FindInterfacesSmokeTest#IGitHubApi.g.verified.cs
Add test for `IObservable<IApiResponse<T>>`
> test: add `IObservable<IApiResponse<T>>` test

- Refit.HttpClientFactory/HttpClientFactoryExtensions.cs
- Refit.Tests/AuthenticatedClientHandlerTests.cs
- Refit.Tests/HttpClientFactoryExtensionsTests.cs
- Refit/AuthenticatedHttpClientHandler.cs
- Refit/UniqueName.cs
This PR fixes #1876.
1. Added new constructor to `AuthenticatedHttpClientHandler` which doesn't automatically set the `InnerHandler` property
2. Adds extension methods to register the Refit client as keyed service
3. Added unit tests
- To keep the PR as small as possible by avoiding the duplication of code
- Enable the a behavior compatible with `IHttpClientBuilder` by ...
- ... avoiding the usage of obsolete functions
- ... avoid setting `InnerHandler`, because this will be done by the builder itself
- `AuthenticatedHttpClientHandler`: Remove the old constructor 
- `AuthenticatedHttpClientHandler`: Remove the `innerHandler` parameter for the new constructor
- `AuthenticatedHttpClientHandler`: Fix the call sites
- Don't call the obsoleted `ConfigureHttpMessageHandlerBuilder`
- Fix the …
> Add the ability to register Refit clients as keyed services

- README.md
Correct the wrong example about JSON source generator in the readme.
The following code shows the difference.
```
public class UnitTest
{
private readonly HttpClient _client = new(new MyHttpMessageHandler());
[Fact]
public async Task Test1()
{
Response? response = null;
var options = MyJsonSerializerContext.Default.Options;
var exception = await Record.ExceptionAsync(async () =>
{
response = await _client.GetFromJsonAsync<Response>("http://abc", options);
});
Assert.Null(exception);
Assert.Equal(1234, response?.Code);
}
[Fact]
public async Task Test2()
{
Response? response = null;
var options = new JsonSerializerOptions()
{
TypeInfoResolver = MyJsonSerializerContext.Default,
};
var exception = await …
```
> Correct the wrong example about JSON source generator in the readme
